# Expanded sample movie/web series/documentary data (100 Hindi movies)
content_list = [
    {"title": "Inception", "type": "Movie", "genre": "Sci-Fi", "language": "English"},
    {"title": "3 Idiots", "type": "Movie", "genre": "Comedy", "language": "Hindi"},
    {"title": "Parasite", "type": "Movie", "genre": "Drama", "language": "Korean"},
    {"title": "Money Heist", "type": "Web Series", "genre": "Crime", "language": "Spanish"},
    {"title": "Dark", "type": "Web Series", "genre": "Sci-Fi", "language": "German"},
    {"title": "The Social Dilemma", "type": "Documentary", "genre": "Documentary", "language": "English"},
    
    # 100 Hindi Movies with Different Types and Genres
    {"title": "Lagaan", "type": "Movie", "genre": "Drama", "language": "Hindi"},
    {"title": "Dangal", "type": "Movie", "genre": "Biography", "language": "Hindi"},
    {"title": "Sholay", "type": "Movie", "genre": "Action", "language": "Hindi"},
    {"title": "Kabhi Khushi Kabhie Gham", "type": "Movie", "genre": "Drama", "language": "Hindi"},
    {"title": "Kuch Kuch Hota Hai", "type": "Movie", "genre": "Romance", "language": "Hindi"},
    {"title": "Zindagi Na Milegi Dobara", "type": "Movie", "genre": "Adventure", "language": "Hindi"},
    {"title": "PK", "type": "Movie", "genre": "Comedy", "language": "Hindi"},
    {"title": "Chennai Express", "type": "Movie", "genre": "Comedy", "language": "Hindi"},
    {"title": "Queen", "type": "Movie", "genre": "Drama", "language": "Hindi"},
    {"title": "Bajrangi Bhaijaan", "type": "Movie", "genre": "Drama", "language": "Hindi"},
    {"title": "Mughal-e-Azam", "type": "Movie", "genre": "Historical", "language": "Hindi"},
    {"title": "Dilwale Dulhania Le Jayenge", "type": "Movie", "genre": "Romance", "language": "Hindi"},
    {"title": "Taare Zameen Par", "type": "Movie", "genre": "Drama", "language": "Hindi"},
    {"title": "Barfi!", "type": "Movie", "genre": "Romance", "language": "Hindi"},
    {"title": "Pyaasa", "type": "Movie", "genre": "Drama", "language": "Hindi"},
    {"title": "Swades", "type": "Movie", "genre": "Drama", "language": "Hindi"},
    {"title": "Andhadhun", "type": "Movie", "genre": "Thriller", "language": "Hindi"},
    {"title": "Gully Boy", "type": "Movie", "genre": "Drama", "language": "Hindi"},
    {"title": "Jab We Met", "type": "Movie", "genre": "Romance", "language": "Hindi"},
    {"title": "Baahubali: The Beginning", "type": "Movie", "genre": "Action", "language": "Hindi"},
    {"title": "Sultan", "type": "Movie", "genre": "Action", "language": "Hindi"},
    {"title": "Zindagi Na Milegi Dobara", "type": "Movie", "genre": "Adventure", "language": "Hindi"},
    {"title": "Don", "type": "Movie", "genre": "Action", "language": "Hindi"},
    {"title": "Raazi", "type": "Movie", "genre": "Thriller", "language": "Hindi"},
    {"title": "Rock On!!", "type": "Movie", "genre": "Drama", "language": "Hindi"},
    {"title": "Dil Chahta Hai", "type": "Movie", "genre": "Drama", "language": "Hindi"},
    {"title": "Dhoom", "type": "Movie", "genre": "Action", "language": "Hindi"},
    {"title": "Kick", "type": "Movie", "genre": "Action", "language": "Hindi"},
    {"title": "Chhichhore", "type": "Movie", "genre": "Comedy", "language": "Hindi"},
    {"title": "Aashiqui 2", "type": "Movie", "genre": "Romance", "language": "Hindi"},
    {"title": "Rang De Basanti", "type": "Movie", "genre": "Drama", "language": "Hindi"},
    {"title": "Barfi!", "type": "Movie", "genre": "Romance", "language": "Hindi"},
    {"title": "Kabir Singh", "type": "Movie", "genre": "Romance", "language": "Hindi"},
    {"title": "Chhakka Panja", "type": "Movie", "genre": "Comedy", "language": "Hindi"},
    {"title": "Bajirao Mastani", "type": "Movie", "genre": "Action", "language": "Hindi"},
    {"title": "Ajab Prem Ki Ghazab Kahani", "type": "Movie", "genre": "Comedy", "language": "Hindi"},
    {"title": "Ae Dil Hai Mushkil", "type": "Movie", "genre": "Romance", "language": "Hindi"},
    {"title": "Sultan", "type": "Movie", "genre": "Action", "language": "Hindi"},
    {"title": "Shuddh Desi Romance", "type": "Movie", "genre": "Romance", "language": "Hindi"},
    {"title": "Sultan", "type": "Movie", "genre": "Action", "language": "Hindi"},
    {"title": "Lagaan", "type": "Movie", "genre": "Drama", "language": "Hindi"},
    {"title": "Wazir", "type": "Movie", "genre": "Thriller", "language": "Hindi"},
    {"title": "Raees", "type": "Movie", "genre": "Action", "language": "Hindi"},
    {"title": "Bajirao Mastani", "type": "Movie", "genre": "Action", "language": "Hindi"},
    {"title": "Judwaa 2", "type": "Movie", "genre": "Comedy", "language": "Hindi"},
    {"title": "Tanu Weds Manu", "type": "Movie", "genre": "Romance", "language": "Hindi"},
    {"title": "Padmaavat", "type": "Movie", "genre": "Action", "language": "Hindi"},
    {"title": "Shree 420", "type": "Movie", "genre": "Comedy", "language": "Hindi"},
    {"title": "Dil Dhadakne Do", "type": "Movie", "genre": "Drama", "language": "Hindi"},
    {"title": "Bajirao Mastani", "type": "Movie", "genre": "Action", "language": "Hindi"},
    {"title": "Jab Tak Hai Jaan", "type": "Movie", "genre": "Romance", "language": "Hindi"},
    {"title": "Tanu Weds Manu", "type": "Movie", "genre": "Romance", "language": "Hindi"},
    {"title": "Chhichhore", "type": "Movie", "genre": "Comedy", "language": "Hindi"},
    {"title": "Sultan", "type": "Movie", "genre": "Action", "language": "Hindi"},
    {"title": "Dilwale Dulhania Le Jayenge", "type": "Movie", "genre": "Romance", "language": "Hindi"},
    {"title": "Queen", "type": "Movie", "genre": "Drama", "language": "Hindi"},
    {"title": "Kuch Kuch Hota Hai", "type": "Movie", "genre": "Romance", "language": "Hindi"},
    {"title": "Kaho Naa... Pyaar Hai", "type": "Movie", "genre": "Romance", "language": "Hindi"},
    {"title": "Aashiqui 2", "type": "Movie", "genre": "Romance", "language": "Hindi"},
    {"title": "Zindagi Na Milegi Dobara", "type": "Movie", "genre": "Adventure", "language": "Hindi"},
    {"title": "Shahrukh Khan", "type": "Movie", "genre": "Biography", "language": "Hindi"},
    {"title": "Kabir Singh", "type": "Movie", "genre": "Romance", "language": "Hindi"},
    {"title": "Kuch Kuch Hota Hai", "type": "Movie", "genre": "Romance", "language": "Hindi"},
    {"title": "Baahubali", "type": "Movie", "genre": "Action", "language": "Hindi"},
    {"title": "Raazi", "type": "Movie", "genre": "Thriller", "language": "Hindi"},
    {"title": "Bajirao Mastani", "type": "Movie", "genre": "Action", "language": "Hindi"},
    # 100 English Movies with Different Types and Genres
     {"title": "The Social Dilemma", "type": "Documentary", "genre": "Documentary", "language": "English"},
    {"title": "The Matrix", "type": "Movie", "genre": "Sci-Fi", "language": "English"},
    {"title": "Avatar", "type": "Movie", "genre": "Sci-Fi", "language": "English"},
    {"title": "Titanic", "type": "Movie", "genre": "Romance", "language": "English"},
    {"title": "The Dark Knight", "type": "Movie", "genre": "Action", "language": "English"},
    {"title": "Forrest Gump", "type": "Movie", "genre": "Drama", "language": "English"},
    {"title": "Pulp Fiction", "type": "Movie", "genre": "Crime", "language": "English"},
    {"title": "Shutter Island", "type": "Movie", "genre": "Mystery", "language": "English"},
    {"title": "The Godfather", "type": "Movie", "genre": "Crime", "language": "English"},
    {"title": "The Shawshank Redemption", "type": "Movie", "genre": "Drama", "language": "English"},
    {"title": "Interstellar", "type": "Movie", "genre": "Sci-Fi", "language": "English"},
    {"title": "Gladiator", "type": "Movie", "genre": "Action", "language": "English"},
    {"title": "The Lord of the Rings", "type": "Movie", "genre": "Fantasy", "language": "English"},
    {"title": "Harry Potter and the Philosopher's Stone", "type": "Movie", "genre": "Fantasy", "language": "English"},
    {"title": "Spider-Man: No Way Home", "type": "Movie", "genre": "Action", "language": "English"},
    {"title": "The Hunger Games", "type": "Movie", "genre": "Adventure", "language": "English"},
    {"title": "Avengers: Endgame", "type": "Movie", "genre": "Action", "language": "English"},
    {"title": "Jumanji", "type": "Movie", "genre": "Adventure", "language": "English"},
    {"title": "The Lion King", "type": "Movie", "genre": "Animation", "language": "English"},
    {"title": "Star Wars: The Force Awakens", "type": "Movie", "genre": "Sci-Fi", "language": "English"},
    {"title": "Inglourious Basterds", "type": "Movie", "genre": "War", "language": "English"},
    {"title": "The Wolf of Wall Street", "type": "Movie", "genre": "Biography", "language": "English"},
    {"title": "The Revenant", "type": "Movie", "genre": "Adventure", "language": "English"},
    {"title": "Coco", "type": "Movie", "genre": "Animation", "language": "Spanish"},
    {"title": "Frozen", "type": "Movie", "genre": "Animation", "language": "English"},
    {"title": "Toy Story", "type": "Movie", "genre": "Animation", "language": "English"},
    {"title": "Deadpool", "type": "Movie", "genre": "Action", "language": "English"},
    {"title": "Guardians of the Galaxy", "type": "Movie", "genre": "Action", "language": "English"},
    {"title": "The Notebook", "type": "Movie", "genre": "Romance", "language": "English"},
    {"title": "The Conjuring", "type": "Movie", "genre": "Horror", "language": "English"},
    {"title": "It", "type": "Movie", "genre": "Horror", "language": "English"},
    {"title": "Wonder Woman", "type": "Movie", "genre": "Action", "language": "English"},
    {"title": "Black Panther", "type": "Movie", "genre": "Action", "language": "English"},
    {"title": "Doctor Strange", "type": "Movie", "genre": "Action", "language": "English"},
    {"title": "Thor: Ragnarok", "type": "Movie", "genre": "Action", "language": "English"},
    {"title": "The Exorcist", "type": "Movie", "genre": "Horror", "language": "English"},
    {"title": "A Quiet Place", "type": "Movie", "genre": "Horror", "language": "English"},
    {"title": "Unforgiven", "type": "Movie", "genre": "Western", "language": "English"},
    {"title": "The Godfather: Part II", "type": "Movie", "genre": "Crime", "language": "English"},
    {"title": "Blade Runner 2049", "type": "Movie", "genre": "Sci-Fi", "language": "English"},
    {"title": "Back to the Future", "type": "Movie", "genre": "Sci-Fi", "language": "English"},
    {"title": "The Prestige", "type": "Movie", "genre": "Mystery", "language": "English"},
    {"title": "Casino Royale", "type": "Movie", "genre": "Action", "language": "English"},
    {"title": "Skyfall", "type": "Movie", "genre": "Action", "language": "English"},
    {"title": "The Martian", "type": "Movie", "genre": "Sci-Fi", "language": "English"},
    {"title": "Hunger", "type": "Movie", "genre": "Drama", "language": "English"},
    {"title": "The Great Gatsby", "type": "Movie", "genre": "Drama", "language": "English"},
    {"title": "The Imitation Game", "type": "Movie", "genre": "Biography", "language": "English"},
    {"title": "Bohemian Rhapsody", "type": "Movie", "genre": "Biography", "language": "English"},
    {"title": "The Pianist", "type": "Movie", "genre": "Biography", "language": "English"},
    {"title": "12 Years a Slave", "type": "Movie", "genre": "Biography", "language": "English"},
    {"title": "La La Land", "type": "Movie", "genre": "Musical", "language": "English"},
    {"title": "The Artist", "type": "Movie", "genre": "Musical", "language": "English"},
    {"title": "Whiplash", "type": "Movie", "genre": "Drama", "language": "English"},
    {"title": "The Big Short", "type": "Movie", "genre": "Biography", "language": "English"},
    {"title": "Dallas Buyers Club", "type": "Movie", "genre": "Biography", "language": "English"},
    {"title": "The Fighter", "type": "Movie", "genre": "Biography", "language": "English"},
    {"title": "The Revenant", "type": "Movie", "genre": "Adventure", "language": "English"},
    {"title": "The Last Samurai", "type": "Movie", "genre": "Action", "language": "English"},
    {"title": "Zootopia", "type": "Movie", "genre": "Animation", "language": "English"},
    {"title": "The Croods", "type": "Movie", "genre": "Animation", "language": "English"},
    {"title": "Kung Fu Panda", "type": "Movie", "genre": "Animation", "language": "English"},
    {"title": "Shrek", "type": "Movie", "genre": "Animation", "language": "English"},
    {"title": "Fifty Shades of Grey", "type": "Movie", "genre": "Romance", "language": "English"},
    {"title": "The Vow", "type": "Movie", "genre": "Romance", "language": "English"},
    {"title": "A Walk to Remember", "type": "Movie", "genre": "Romance", "language": "English"},
    {"title": "Crazy, Stupid, Love", "type": "Movie", "genre": "Romance", "language": "English"},
    {"title": "To All the Boys I’ve Loved Before", "type": "Movie", "genre": "Romance", "language": "English"},
    {"title": "500 Days of Summer", "type": "Movie", "genre": "Romance", "language": "English"},
    {"title": "The Fault in Our Stars", "type": "Movie", "genre": "Romance", "language": "English"},
    {"title": "Before Sunrise", "type": "Movie", "genre": "Romance", "language": "English"},
    {"title": "Her", "type": "Movie", "genre": "Romance", "language": "English"},
    {"title": "Titanic", "type": "Movie", "genre": "Romance", "language": "English"},
    {"title": "The Proposal", "type": "Movie", "genre": "Romance", "language": "English"},
    {"title": "Wedding Crashers", "type": "Movie", "genre": "Comedy", "language": "English"},
    {"title": "Superbad", "type": "Movie", "genre": "Comedy", "language": "English"},
    {"title": "21 Jump Street", "type": "Movie", "genre": "Comedy", "language": "English"},
    {"title": "Step Brothers", "type": "Movie", "genre": "Comedy", "language": "English"},
    {"title": "Dumb and Dumber", "type": "Movie", "genre": "Comedy", "language": "English"},

      # 100 Korean Movies with Different Types and Genres
     {"title": "Parasite", "type": "Movie", "genre": "Drama", "language": "Korean"},
    {"title": "Oldboy", "type": "Movie", "genre": "Thriller", "language": "Korean"},
    {"title": "Train to Busan", "type": "Movie", "genre": "Horror", "language": "Korean"},
    {"title": "The Handmaiden", "type": "Movie", "genre": "Thriller", "language": "Korean"},
    {"title": "The Host", "type": "Movie", "genre": "Sci-Fi", "language": "Korean"},
    {"title": "Memories of Murder", "type": "Movie", "genre": "Crime", "language": "Korean"},
    {"title": "Snowpiercer", "type": "Movie", "genre": "Sci-Fi", "language": "Korean"},
    {"title": "I Saw the Devil", "type": "Movie", "genre": "Thriller", "language": "Korean"},
    {"title": "Mother", "type": "Movie", "genre": "Drama", "language": "Korean"},
    {"title": "A Bittersweet Life", "type": "Movie", "genre": "Action", "language": "Korean"},
    {"title": "The Man from Nowhere", "type": "Movie", "genre": "Action", "language": "Korean"},
    {"title": "My Sassy Girl", "type": "Movie", "genre": "Romance", "language": "Korean"},
    {"title": "The Age of Shadows", "type": "Movie", "genre": "Thriller", "language": "Korean"},
    {"title": "The Wailing", "type": "Movie", "genre": "Horror", "language": "Korean"},
    {"title": "Secret Zoo", "type": "Movie", "genre": "Comedy", "language": "Korean"},
    {"title": "The Chaser", "type": "Movie", "genre": "Thriller", "language": "Korean"},
    {"title": "The Battles Without Honor and Humanity", "type": "Movie", "genre": "Action", "language": "Korean"},
    {"title": "The King", "type": "Movie", "genre": "Action", "language": "Korean"},
    {"title": "The Drug King", "type": "Movie", "genre": "Crime", "language": "Korean"},
    {"title": "The Admiral: Roaring Currents", "type": "Movie", "genre": "Action", "language": "Korean"},
    {"title": "Time to Hunt", "type": "Movie", "genre": "Thriller", "language": "Korean"},
    {"title": "Along with the Gods: The Two Worlds", "type": "Movie", "genre": "Fantasy", "language": "Korean"},
    {"title": "The Villainess", "type": "Movie", "genre": "Action", "language": "Korean"},
    {"title": "The Queen of Black Magic", "type": "Movie", "genre": "Horror", "language": "Korean"},
    {"title": "The Spy Gone North", "type": "Movie", "genre": "Thriller", "language": "Korean"},
    {"title": "The Tower", "type": "Movie", "genre": "Disaster", "language": "Korean"},
    {"title": "Oasis", "type": "Movie", "genre": "Drama", "language": "Korean"},
    {"title": "Crush and Blush", "type": "Movie", "genre": "Comedy", "language": "Korean"},
    {"title": "The Thieves", "type": "Movie", "genre": "Action", "language": "Korean"},
    {"title": "The Drug King", "type": "Movie", "genre": "Crime", "language": "Korean"},
    {"title": "Happiness", "type": "Web Series", "genre": "Horror", "language": "Korean"},
    {"title": "Vagabond", "type": "Web Series", "genre": "Action", "language": "Korean"},
    {"title": "Stranger", "type": "Web Series", "genre": "Thriller", "language": "Korean"},
    {"title": "Kingdom", "type": "Web Series", "genre": "Horror", "language": "Korean"},
    {"title": "Mr. Sunshine", "type": "Web Series", "genre": "Drama", "language": "Korean"},
    {"title": "Signal", "type": "Web Series", "genre": "Thriller", "language": "Korean"},
    {"title": "Boys Over Flowers", "type": "Web Series", "genre": "Romance", "language": "Korean"},
    {"title": "Reply 1988", "type": "Web Series", "genre": "Drama", "language": "Korean"},
    {"title": "The Uncanny Counter", "type": "Web Series", "genre": "Fantasy", "language": "Korean"},
    {"title": "Life", "type": "Web Series", "genre": "Drama", "language": "Korean"},
    {"title": "It's Okay to Not Be Okay", "type": "Web Series", "genre": "Drama", "language": "Korean"},
    {"title": "Youth of May", "type": "Web Series", "genre": "Romance", "language": "Korean"},
    {"title": "Healer", "type": "Web Series", "genre": "Action", "language": "Korean"},
    {"title": "My Mister", "type": "Web Series", "genre": "Drama", "language": "Korean"},
    {"title": "Squid Game", "type": "Web Series", "genre": "Thriller", "language": "Korean"},
    {"title": "Sky Castle", "type": "Web Series", "genre": "Drama", "language": "Korean"},
    {"title": "Touch Your Heart", "type": "Web Series", "genre": "Romance", "language": "Korean"},
    {"title": "The Heirs", "type": "Web Series", "genre": "Romance", "language": "Korean"},
    {"title": "The Penthouse", "type": "Web Series", "genre": "Drama", "language": "Korean"},
    {"title": "Stranger 2", "type": "Web Series", "genre": "Thriller", "language": "Korean"},
    {"title": "Reply 1997", "type": "Web Series", "genre": "Drama", "language": "Korean"},
    {"title": "Misaeng", "type": "Web Series", "genre": "Drama", "language": "Korean"},
    {"title": "W", "type": "Web Series", "genre": "Fantasy", "language": "Korean"},
    {"title": "Cinderella and Four Knights", "type": "Web Series", "genre": "Romance", "language": "Korean"},
    {"title": "My Lovely Sam Soon", "type": "Web Series", "genre": "Romance", "language": "Korean"},
    {"title": "The Flower of Evil", "type": "Web Series", "genre": "Thriller", "language": "Korean"},
    {"title": "Secret Garden", "type": "Web Series", "genre": "Fantasy", "language": "Korean"},
    {"title": "The King: Eternal Monarch", "type": "Web Series", "genre": "Fantasy", "language": "Korean"},
    {"title": "It's Okay to Not Be Okay", "type": "Web Series", "genre": "Drama", "language": "Korean"},
    {"title": "Train to Busan", "type": "Movie", "genre": "Horror", "language": "Korean"},
    {"title": "Itaewon Class", "type": "Web Series", "genre": "Drama", "language": "Korean"},
    {"title": "My ID is Gangnam Beauty", "type": "Web Series", "genre": "Romance", "language": "Korean"},
    {"title": "Tomorrow with You", "type": "Web Series", "genre": "Romance", "language": "Korean"},
    {"title": "Boys Over Flowers", "type": "Web Series", "genre": "Romance", "language": "Korean"},
    {"title": "The Smile Has Left Your Eyes", "type": "Web Series", "genre": "Drama", "language": "Korean"},
    {"title": "Vincenzo", "type": "Web Series", "genre": "Crime", "language": "Korean"},
    {"title": "Wok of Love", "type": "Web Series", "genre": "Romance", "language": "Korean"},
    {"title": "Running Man", "type": "Web Series", "genre": "Reality", "language": "Korean"},

# 100 Spanish Movies with Different Types and Genres
    {"title": "La Casa de Papel", "type": "Web Series", "genre": "Crime", "language": "Spanish"},
    {"title": "Pan's Labyrinth", "type": "Movie", "genre": "Fantasy", "language": "Spanish"},
    {"title": "The Orphanage", "type": "Movie", "genre": "Horror", "language": "Spanish"},
    {"title": "The Secret in Their Eyes", "type": "Movie", "genre": "Thriller", "language": "Spanish"},
    {"title": "Talk to Her", "type": "Movie", "genre": "Drama", "language": "Spanish"},
    {"title": "The Skin I Live In", "type": "Movie", "genre": "Thriller", "language": "Spanish"},
    {"title": "Volver", "type": "Movie", "genre": "Drama", "language": "Spanish"},
    {"title": "The Others", "type": "Movie", "genre": "Horror", "language": "Spanish"},
    {"title": "Y Tu Mamá También", "type": "Movie", "genre": "Drama", "language": "Spanish"},
    {"title": "Biutiful", "type": "Movie", "genre": "Drama", "language": "Spanish"},
    {"title": "The Motorcycle Diaries", "type": "Movie", "genre": "Biography", "language": "Spanish"},
    {"title": "Cría Cuervos", "type": "Movie", "genre": "Drama", "language": "Spanish"},
    {"title": "La La Land", "type": "Movie", "genre": "Romance", "language": "Spanish"},
    {"title": "The Invisible Guest", "type": "Movie", "genre": "Thriller", "language": "Spanish"},
    {"title": "The Sea Inside", "type": "Movie", "genre": "Drama", "language": "Spanish"},
    {"title": "The Hand of God", "type": "Movie", "genre": "Drama", "language": "Spanish"},
    {"title": "The Queen of Spain", "type": "Movie", "genre": "Comedy", "language": "Spanish"},
    {"title": "Coco", "type": "Movie", "genre": "Animation", "language": "Spanish"},
    {"title": "Volver", "type": "Movie", "genre": "Drama", "language": "Spanish"},
    {"title": "El Laberinto del Fauno", "type": "Movie", "genre": "Fantasy", "language": "Spanish"},
    {"title": "Tesis", "type": "Movie", "genre": "Thriller", "language": "Spanish"},
    {"title": "La Piel Que Habito", "type": "Movie", "genre": "Thriller", "language": "Spanish"},
    {"title": "La Lengua de las Mariposas", "type": "Movie", "genre": "Drama", "language": "Spanish"},
    {"title": "El Secreto de Sus Ojos", "type": "Movie", "genre": "Drama", "language": "Spanish"},
    {"title": "El Cuerpo", "type": "Movie", "genre": "Thriller", "language": "Spanish"},
    {"title": "La Casa de Papel", "type": "Web Series", "genre": "Crime", "language": "Spanish"},
    {"title": "Money Heist", "type": "Web Series", "genre": "Crime", "language": "Spanish"},
    {"title": "Narcos", "type": "Web Series", "genre": "Crime", "language": "Spanish"},
    {"title": "Vis a Vis", "type": "Web Series", "genre": "Thriller", "language": "Spanish"},
    {"title": "La Casa de las Flores", "type": "Web Series", "genre": "Comedy", "language": "Spanish"},
    {"title": "El Ministerio del Tiempo", "type": "Web Series", "genre": "Sci-Fi", "language": "Spanish"},
    {"title": "Gran Hotel", "type": "Web Series", "genre": "Drama", "language": "Spanish"},
    {"title": "El Internado", "type": "Web Series", "genre": "Thriller", "language": "Spanish"},

    # 100 German Movies with Different Types and Genres
      {"title": "Das Leben der Anderen", "type": "Movie", "genre": "Drama", "language": "German"},
    {"title": "Good Bye Lenin!", "type": "Movie", "genre": "Comedy", "language": "German"},
    {"title": "Run Lola Run", "type": "Movie", "genre": "Thriller", "language": "German"},
    {"title": "The Lives of Others", "type": "Movie", "genre": "Drama", "language": "German"},
    {"title": "Downfall", "type": "Movie", "genre": "War", "language": "German"},
    {"title": "The Baader Meinhof Complex", "type": "Movie", "genre": "Drama", "language": "German"},
    {"title": "The Wave", "type": "Movie", "genre": "Drama", "language": "German"},
    {"title": "The Counterfeiters", "type": "Movie", "genre": "Drama", "language": "German"},
    {"title": "Barbara", "type": "Movie", "genre": "Drama", "language": "German"},
    {"title": "Cloud Atlas", "type": "Movie", "genre": "Sci-Fi", "language": "German"},
    {"title": "Toni Erdmann", "type": "Movie", "genre": "Comedy", "language": "German"},
    {"title": "The White Ribbon", "type": "Movie", "genre": "Drama", "language": "German"},
    {"title": "The Princess and the Warrior", "type": "Movie", "genre": "Romance", "language": "German"},
    {"title": "The International", "type": "Movie", "genre": "Thriller", "language": "German"},
    {"title": "M", "type": "Movie", "genre": "Thriller", "language": "German"},
    {"title": "Wings of Desire", "type": "Movie", "genre": "Fantasy", "language": "German"},
    {"title": "Stalingrad", "type": "Movie", "genre": "War", "language": "German"},
    {"title": "Fury", "type": "Movie", "genre": "War", "language": "German"},
    {"title": "Labyrinth of Lies", "type": "Movie", "genre": "Drama", "language": "German"},
    {"title": "A Coffee in Berlin", "type": "Movie", "genre": "Comedy", "language": "German"},
    {"title": "The Edukators", "type": "Movie", "genre": "Drama", "language": "German"},
    {"title": "Phoenix", "type": "Movie", "genre": "Drama", "language": "German"},
    {"title": "Soul Kitchen", "type": "Movie", "genre": "Comedy", "language": "German"},
    {"title": "Labyrinth of Lies", "type": "Movie", "genre": "Drama", "language": "German"},
    {"title": "The Boat", "type": "Movie", "genre": "Thriller", "language": "German"},
    {"title": "The Wave", "type": "Movie", "genre": "Drama", "language": "German"},
    {"title": "Oasis", "type": "Movie", "genre": "Drama", "language": "German"},
    {"title": "Youth", "type": "Movie", "genre": "Drama", "language": "German"},
    {"title": "Fatih Akin", "type": "Movie", "genre": "Drama", "language": "German"},
    {"title": "The Girl with the Dragon Tattoo", "type": "Movie", "genre": "Thriller", "language": "German"},
    {"title": "Me and Earl and the Dying Girl", "type": "Movie", "genre": "Drama", "language": "German"},
    {"title": "Zwei Leben", "type": "Movie", "genre": "Drama", "language": "German"},
    {"title": "The White Ribbon", "type": "Movie", "genre": "Drama", "language": "German"},
    {"title": "The Pact", "type": "Movie", "genre": "Drama", "language": "German"},
    {"title": "Das Experiment", "type": "Movie", "genre": "Thriller", "language": "German"},
    {"title": "Monuments Men", "type": "Movie", "genre": "War", "language": "German"},
    {"title": "Die Welle", "type": "Movie", "genre": "Drama", "language": "German"},
    {"title": "Good Bye Lenin!", "type": "Movie", "genre": "Comedy", "language": "German"},
    {"title": "The Lives of Others", "type": "Movie", "genre": "Drama", "language": "German"},
    {"title": "Downfall", "type": "Movie", "genre": "War", "language": "German"},
    {"title": "The Princess and the Warrior", "type": "Movie", "genre": "Romance", "language": "German"},
    {"title": "The White Ribbon", "type": "Movie", "genre": "Drama", "language": "German"},
    {"title": "Fury", "type": "Movie", "genre": "War", "language": "German"},
    {"title": "Labyrinth of Lies", "type": "Movie", "genre": "Drama", "language": "German"},
    {"title": "Berlin Alexanderplatz", "type": "Web Series", "genre": "Drama", "language": "German"},
    {"title": "Deutschland 83", "type": "Web Series", "genre": "Drama", "language": "German"},
    {"title": "Babylon Berlin", "type": "Web Series", "genre": "Crime", "language": "German"},
    {"title": "Deutschland 86", "type": "Web Series", "genre": "Drama", "language": "German"},
    {"title": "We Are the Wave", "type": "Web Series", "genre": "Drama", "language": "German"},
    {"title": "Dark", "type": "Web Series", "genre": "Sci-Fi", "language": "German"},
    {"title": "Tatort", "type": "Web Series", "genre": "Crime", "language": "German"},
    {"title": "Biohackers", "type": "Web Series", "genre": "Thriller", "language": "German"}

]

# Valid options
types = ["Movie", "Web Series", "Documentary"]
genres = ["Sci-Fi", "Comedy", "Drama", "Crime", "Documentary", "Action", "Romance", "Fantasy", "Animation", "Mystery", "Adventure", "Biography", "War"]
languages = ["English", "Hindi", "Korean", "Spanish", "German"]

# Get validated input
def get_input(prompt, options):
    while True:
        user_input = input(f"{prompt} ({', '.join(options)}): ").strip()
        if user_input.title() in options:
            return user_input.title()
        else:
            print("❌ Invalid input. Please try again.\n")

# Main logic
def recommend():
    print("\n🎬 Welcome to the Content Recommendation System 🎬\n")

    content_type = get_input("Choose type", types)
    genre = get_input("Choose genre", genres)
    language = get_input("Choose language", languages)

    # Filter and recommend
    matches = [
        c["title"] for c in content_list
        if c["type"] == content_type and c["genre"] == genre and c["language"] == language
    ]

    if matches:
        print("\n✅ We recommend you watch:")
        for title in matches:
            print(f"👉 {title}")
    else:
        print("\n😔 No content found for that combination.")

# Run the recommender
recommend()